[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "npx sequelize-cli db:migrate --migrations-path src/migrations || true && npx sequelize-cli db:seed:all --seeders-path src/seeders || true && node src/server.js"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
