[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "npx sequelize-cli db:migrate --migrations-path src/migrations && npx sequelize-cli db:seed:all --seeders-path src/seeders 2>/dev/null; node src/server.js"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
